### ISSUE TITLE
Create Documentation Team

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/blackpythondevs#62]
# Create Documentation Team

Due Date: 1 June

Description:

We want to create a group for folks that are wanting to get into Documentation. This would be our documentation group and would focus on giving folks the ability to contribute to the community while learning valuable documenation coordination skills around open source.

### Tasks:

- [x] Identify Documentation Leader
- [x] Create Documentation team on GitHub
- [x] Create role documentation for documentation team
- [x] Create a yagpbd command for documentation team
- [X] create label for documentation
- [ ] document roles and responsibilities
- [ ] create GitHub webhook for documentation labels to ping documenation role

**Comment by ronnzw** [comment]
It would be good to find someone else in the community to lead this but if we don't have anyone willing to take this role then I'm happy to run with this.
