### ISSUE TITLE
PyCon NG 2024_____ Checklist 

### ISSUE THREAD

**Issue by AlphaCodz** [BlackPythonDevs/blackpythondevs#97]
# Check Lists

- [x] Receive the Customized BPD shirts from AlphaMode
- [x] Pay for the Hotel
- [x] Finalize the Ticket sharing procedures for the remaining tickets
- [x] Go through Key Note speech Slides
- [x] Find Alternative Payment method for Donations to BPD for people who can't make dollar payments through the QR code.

**Comment by kjaymiller** [comment]
> Pay for the Hotel
Money was sent to Nuel to pay for Hotel

**Comment by kjaymiller** [comment]
> Find Alternative Payment method for Donations to BPD for people who can't make dollar payments through the QR code.

For this is there a service that you can collect the funds in Naira? Like even your personal paypal or something?

**Comment by AlphaCodz** [comment]
> > Pay for the Hotel
> > Money was sent to Nuel to pay for Hotel

Yes I'm aware. When we do make the payment we will check it off the list. We are working on everything on the list, you don't need to worry yourself about it. It's just here so that you are in loop of everything we're doing.

**Comment by AlphaCodz** [comment]
> > Find Alternative Payment method for Donations to BPD for people who can't make dollar payments through the QR code.
> 
> For this is there a service that you can collect the funds in Naira? Like even your personal paypal or something?

Yes Sir, we are working on it.
We will look at the best way to go and let you know by tonight
